module.exports = {
  SESSION_STATUS: {
    NOT_STARTED: 'NOT_STARTED',
    ON_GOING: 'ON_GOING',
    COMPLETE: 'COMPLETE',
    DRAFT: 'DRAFT',
    PUBLISHED: 'PUBLISHED',
    ARCHIVED: 'ARCHIVED',
    DELETED: 'DELETED',
  },
  SESSION_STATUS_TRANSITIONS: {
    DRAFT: ['PUBLISHED', 'DELETED'],
    NOT_STARTED: ['ON_GOING', 'DRAFT', 'DELETED'],
    ON_GOING: ['COMPLETE', 'DELETED'],
    COMPLETE: ['PUBLISHED', 'ARCHIVED', 'DELETED'],
    PUBLISHED: ['ARCHIVED', 'DELETED'],
    ARCHIVED: ['PUBLISHED', 'DELETED'],
    DELETED: [],
  },
  SESSION_REQUEST_STATUS: {
    PENDING: 'pending',
    APPROVED: 'approved',
    REJECTED: 'rejected',
  },
  TOPIC_STATUS: {
    APPROVED: 'approved',
    REJECTED: 'rejected',
    DRAFT: 'draft',
    SUBMITED: 'submited',
    ARCHIVED: 'archived',
  },
  SECTION_STATUS: {
    DRAFT: 'draft',
    PUBLISHED: 'published',
    ARCHIVED: 'archived',
  },
  skillMapping: {
    READING: 'Reading',
    LISTENING: 'Listening',
    WRITING: 'Writing',
    SPEAKING: 'Speaking',
    'GRAMMAR AND VOCABULARY': 'GrammarVocab',
  },
  skillIDMapping: {
    READING: '',
    LISTENING: '',
    WRITING: '',
    SPEAKING: '',
    GRAMMAR_VOCAB: '',
  },
  questionTypeMapping: {
    WRITING: 'writing',
    SPEAKING: 'speaking',
    MULTIPLE_CHOICE: 'multiple-choice',
    ORDERING: 'ordering',
    DROPDOWN_LIST: 'dropdown-list',
    MATCHING: 'matching',
    LISTENING_QUESTION_GROUP: 'listening-question-group',
  },
  skillMappingLevel: {
    READING: 'ReadingLevel',
    LISTENING: 'ListeningLevel',
    WRITING: 'WritingLevel',
    SPEAKING: 'SpeakingLevel',
  },
  pointsPerQuestion: {
    listening: 2,
    GrammarVocab: 1,
    reading: 50 / 29,
  },
  level: {
    X: 'X',
    A1: 'A1',
    A2: 'A2',
    B1: 'B1',
    B2: 'B2',
    C: 'C',
  },
};
